### ISSUE TITLE
Add permission to the Setting Page

### ISSUE THREAD

**Issue by Fanom2813** [tomatophp/filament-pwa#1]
how to hide the setting menu item from other users like normal users , and only show on admin

**Comment by Faezz001** [comment]
My filament uses Filament Shield for access control yet user can still access the settings.

**Comment by 3x1io** [comment]
check the last version

**Comment by Gjentii** [comment]
The permission is not working for me.
I have the shield plugin does it have something to do with me having a having a Settings custom page because it is not working
for the PWA Setting Page

**Comment by 3x1io** [comment]
i think you need to allow discover page and resources and widgets on your shield.php config
