### ISSUE TITLE
The `install` icon on the address bar is not showing on production

### ISSUE THREAD

**Issue by hussain4real** [tomatophp/filament-pwa#2]
The PWA feature seems not to be working in production, though works on mobile
<img width="208" alt="Screenshot 2024-08-07 at 14 49 27" src="https://github.com/user-attachments/assets/c6fc50c9-4751-4049-8b35-51a97de1828d">

**Comment by hussain4real** [comment]
works if you change the `FILESYSTEM_DISK` to `public`

**Comment by 3x1io** [comment]
@hussain4real because we try to access the images and PWA files on public
