### ISSUE TITLE
Problem in the admin panel

### ISSUE THREAD

**Issue by MastersCon** [tomatophp/filament-pwa#3]
I installed everything with the guide you provided, but I don't know why the admin panel gives me this error, in the config setting the spaties appears as unrecognized, I have filament v3 and laravel 10, there I leave you my adminpanelprovider too, I don't see that the setting resource is created in the project since I see that in the image you show the setting, that is, I don't know if you include it for the resource, but anyway is there a video tutorial because I try to install the pwa and nothing and I do all the steps

![image](https://github.com/user-attachments/assets/2de7ac11-7567-42c7-b7e5-87963b493c78)

![image](https://github.com/user-attachments/assets/55af604d-ab8a-41d8-ba4d-a8215bd3e1bd)

![image](https://github.com/user-attachments/assets/346361e9-984e-457d-be11-a2d396aa578b)

**Comment by 3x1io** [comment]
hi @MastersCon I think your problem is with the filament part, there is no HOOK to attach the PWA script. and that's a problem so try to upgrade your filament version or check if the hook exists.

**Comment by RawanD201** [comment]
same problem

**Comment by 3x1io** [comment]
can you try use this command 

```
php artisan filament:optimize
```

**Comment by 3x1io** [comment]
this plugin only supports v3.2 so please upgrade your filament package
