### ISSUE TITLE
Make filament app work without internet.

### ISSUE THREAD

**Issue by saifonglee** [tomatophp/filament-pwa#5]
HI, this is just a question, 
I've to make company's app work offline and online. mean that when no internet, app continue to work and when connection is established, update/sync is made to keep both updated. 

is filament-wpa able to do that or i've to do some implementation additionaly to acheive this?
if not, is there an service on line which can permit me to do that?
or can you guide me on how to do that in filament?

i appreciate your help!

**Comment by 3x1io** [comment]
sorry, there is no way to make FilamentPHP or Livewire app work without the internet because it requires server rendering and if the server is offline it will not work!, and it's out of our scope for this plugin.
